#
###################################
# Site wide configuration
####################################
#
title: Leeds Hacking Society
email: leedshackingsociety@gmail.com
description: Leeds Hacking Society Website
url: www.leedshackingsociety.co.uk # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/London
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Leeds Hacking Society
  avatar: profile.png
  bio: "Welcome to the Leeds Hacking Society Website, we are a student-led Society at Leeds Beckett University."
  email: leedshackingsociety@gmail.com
  disqus-shortname: LeedsHackingSociety
  twitter: leedsehs #username
  facebook: leedshackingsociety #username
  github: LeedsHackingSociety #username
  google:
    plus:  #username
    analytics: UA-97458188-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
